/**
 * Defines all possible sub systems that can be secured by roles.
 */
export enum Permission {
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  RULE_CREATE = 'RULE_CREATE',
  RULE_READ = 'RULE_READ',
  RULE_UPDATE = 'RULE_UPDATE',
  RULE_DELETE = 'RULE_DELETE',

  DEVICE_CREATE = 'DEVICE_CREATE',
  DEVICE_READ = 'DEVICE_READ',
  DEVICE_UPDATE = 'DEVICE_UPDATE',
  DEVICE_DELETE = 'DEVICE_DELETE',

  DEVICE_TYPE_CREATE = 'DEVICE_TYPE_CREATE',
  DEVICE_TYPE_READ = 'DEVICE_TYPE_READ',
  DEVICE_TYPE_UPDATE = 'DEVICE_TYPE_UPDATE',
  DEVICE_TYPE_DELETE = 'DEVICE_TYPE_DELETE',

  POINT_CREATE = 'POINT_CREATE',
  POINT_READ = 'POINT_READ',
  POINT_UPDATE = 'POINT_UPDATE',
  POINT_DELETE = 'POINT_DELETE',

  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_READ = 'ROLE_READ',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  DASHBOARD_CREATE = 'DASHBOARD_CREATE',
  DASHBOARD_READ = 'DASHBOARD_READ',
  DASHBOARD_UPDATE = 'DASHBOARD_UPDATE',
  DASHBOARD_DELETE = 'DASHBOARD_DELETE',

  REPORT_CREATE = 'REPORT_CREATE',
  REPORT_READ = 'REPORT_READ',
  REPORT_UPDATE = 'REPORT_UPDATE',
  REPORT_DELETE = 'REPORT_DELETE',

  TEMPLATE_CREATE = 'TEMPLATE_CREATE',
  TEMPLATE_READ = 'TEMPLATE_READ',
  TEMPLATE_UPDATE = 'TEMPLATE_UPDATE',
  TEMPLATE_DELETE = 'TEMPLATE_DELETE',

  NOTIFICATION_READ = 'NOTIFICATION_READ',

  MOBILE_READ = 'MOBILE_READ',

  CONTEXT_MANAGEMENT = 'CONTEXT_MANAGEMENT',

  DELETE_OWN_ACCOUNT = 'DELETE_OWN_ACCOUNT',

  DATA_PUBLISH = 'DATA_PUBLISH'
}
